name: Publish Python Package to PyPI

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        run: |
          python -m twine upload \
            --username __token__ \
            --password "${{ secrets.PYPI_API_TOKEN }}" \
            dist/*
